### ISSUE TITLE
More control on postprocessor

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkiweb#10]
It would be useful to have some more fine grained control over the postprocessor ('s command-line arguments) on a dataset by dataset basis, e.g. disabling dba_qcfilter on json postprocessor on a specific ds.
Could it be done e.g. with a key in config?

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
