### ISSUE TITLE
refine download size policies

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkiweb#9]
riassunto di elucubrazioni con @edigiacomo :
 - `ARKIWEB_MAXCOUNT` e `ARKIWEB_MAXSIZE` sono documentati e definiti ma non implementati. Il summary di arkimet potrebbe essere inaffidabile quindi forse conviene cambiare approccio
 - il webservice `/data` al momento è accessibile anche senza specificare query e questo si potrebbe parare
 - si potrebbero definire limiti tipo: periodo di estrazione (definito in termini assoluti o per dataset/utente analizzando la query)

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
